services:
  app:
    build: 
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:1.27.4
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app