services:
  app:
    build: 
      context: .
      dockerfile: docker/Dockerfile.dev
    env_file:
      - .env.dev
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:1.27.4
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  
  db:
    image: mysql:9.2.0
    env_file:
      - .env.dev
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-data: